version: "3.9"

volumes:
  mysql_data:

services:
  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      # - 8080:8080 # dashboard
      # - ${MYSQL_PORT}:3306 # mysql
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./configs/traefik.yml:/etc/traefik/traefik.yml:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=PathPrefix(`/api`, `/dashboard`)
      - traefik.http.routers.dashboard.service=api@internal
      # - traefik.http.routers.traefik.rule=Host(`${AZURE_DDNS}`)

  mysql:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.mysql.rule=HostSNI(`*`)
      - traefik.tcp.routers.mysql.entryPoints=mysql
      - traefik.tcp.routers.mysql.service=mysql
      - traefik.tcp.services.mysql.loadbalancer.server.port=3306

  fiber:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY}/nutbooks-api
    restart: unless-stopped
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    command: 
      - /bin/bash
      - -c
      - |
        /wait-for-it.sh -t 10 ${MYSQL_HOST}:${MYSQL_PORT} -- /main run
    labels:
      - traefik.enable=true
      - traefik.http.routers.fiber.rule=PathPrefix(`/`)
      - traefik.http.services.fiber.loadbalancer.server.port=${API_PORT}
