version: "3.9"

volumes:
  mysql_data:

services:
  db:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY}/nutbooks-api
    restart: unless-stopped
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      API_PORT: ${API_PORT}
    command: 
      - /bin/bash
      - -c
      - |
        /wait-for-it.sh -t 10 ${MYSQL_HOST}:${MYSQL_PORT} -- /main run
