# https://code-yeongyu.tistory.com/36

FROM golang:1.20-alpine AS builder
LABEL authors="cheesecat47 <cheesecat47@gmail.com>"

RUN apk update

WORKDIR /build

ENV GO111MODULE=on \
    CGO_ENABLE=0 \
    GOOS=linux

COPY go.mod .
COPY go.sum .
RUN go mod tidy && go install github.com/cosmtrek/air@latest

COPY . .
RUN go clean -cache

RUN apk update && apk add --no-cache bash
