version: "3.9"

volumes:
  mysql_data:

services:
  db:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY}/bookmarks-api
    restart: unless-stopped
    depends_on:
      - db
