definitions:
  controllers.AddBookmarkJsonRequest:
    properties:
      link:
        example: https://cheesecat47.github.io
        type: string
      title:
        type: string
      user_id:
        type: integer
    type: object
  controllers.GetAllBookmarksJSONResult:
    properties:
      data:
        items: {}
        type: array
      error:
        type: boolean
      message:
        type: string
    type: object
  controllers.GetBookmarkByIdJSONResult:
    properties:
      data: {}
      error:
        type: boolean
      message:
        type: string
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.AddUserRequest:
    properties:
      email:
        example: ""
        type: string
      name:
        example: ""
        type: string
    required:
    - email
    - name
    type: object
  models.AddUserResponse:
    properties:
      data: {}
      error:
        type: boolean
      message:
        type: string
    type: object
  models.GetUserByIdResponse:
    properties:
      data: {}
      error:
        type: boolean
      message:
        type: string
    type: object
  models.User:
    properties:
      Authority:
        type: string
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/:
    get:
      responses:
        "200":
          description: OK
      summary: Root URL - for health check
      tags:
      - /
  /api/v1/bookmark:
    get:
      parameters:
      - description: limit과 offset은 같이 입력해야 합니다
        in: query
        name: offset
        type: integer
      - description: limit과 offset은 같이 입력해야 합니다
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.GetAllBookmarksJSONResult'
        "400":
          description: Bad Request
      summary: offset부터 limit까지 북마크 목록을 반환
      tags:
      - bookmark
  /api/v1/bookmark/:
    post:
      consumes:
      - application/json
      description: 새 북마크를 DB에 저장. 북마크 링크는 필수 데이터이고, 그 외는 옵셔널.
      parameters:
      - description: body params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controllers.AddBookmarkJsonRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: 북마크를 DB에 추가하는 API
      tags:
      - bookmark
  /api/v1/bookmark/{id}:
    get:
      parameters:
      - description: Bookmark ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.GetBookmarkByIdJSONResult'
        "400":
          description: Bad Request
      summary: ID를 사용해 북마크 1개 정보 읽기
      tags:
      - bookmark
  /api/v1/user/:
    post:
      parameters:
      - description: body params
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/models.AddUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.AddUserResponse'
            - properties:
                data:
                  $ref: '#/definitions/models.User'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.AddUserResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.AddUserResponse'
      summary: 새 유저를 추가하는 API
      tags:
      - user
  /api/v1/user/{id}:
    get:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.GetUserByIdResponse'
            - properties:
                data:
                  $ref: '#/definitions/models.User'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.GetUserByIdResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.AddUserResponse'
      summary: UserID를 사용해 유저 1명 정보 읽기
      tags:
      - user
swagger: "2.0"
